@tool
class_name MapModifierNoise extends MapModifier
# Changes tiles based on noise generated by the FastNoiseLite resource.

@export var noise: FastNoiseLite = FastNoiseLite.new()
@export_range(-1.0, 1.0) var threshold: float = 0.0
@export var tile: Tile = Tile.new()
@export var tile_mask: Array[Tile] = [Tile.new()]

func modify(map: ProceduralMap) -> void:
	noise.seed = map.rng.seed
	for x in range(map.size.x):
		for y in range(map.size.y):
			var coords := Vector2i(x, y)
			var map_tile := map.get_cell_tile(coords)
			if !tile_mask.any(map_tile.equals):
				continue
			if noise.get_noise_2dv(coords) < threshold:
				continue
			map.set_cell_tile(coords, tile)
